version: '3.8'  # 指定docker-compose版本语法

services:
  # fastapi backend
  apex_server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: apex_server
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - apex_mysql
      - apex_redis
      - apex_celery
    networks:
      - apex_network
    command: ["gunicorn","-c","gunicorn.conf.py","testframe_backend.main:app"]

  # celery服务
  apex_celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: apex_celery
    restart: always
    depends_on:
      - apex_redis
      - apex_mysql
    networks:
      - apex_network
    command:
      - bash
      - -c
      - |
        mkdir -p /var/log/supervisor/
        supervisord -c /app/testframe_backend/conf/supervisor.conf
        supervisorctl restart celery_worker
        supervisorctl restart celery_beat
  # redis服务
  apex_redis:
    image: redis:7.2.0
    container_name: apex_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 123456
    volumes:
      - apex_redis:/data
    networks:
      - apex_network
  # mysql服务
  apex_mysql:
    image: mysql:8.1.0
    container_name: apex_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: apex
      TZ: Asia/Shanghai
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - apex_mysql:/var/lib/mysql
    networks:
      - apex_network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --lower_case_table_names=1

networks:
  apex_network:
    driver: bridge

volumes:
  apex_mysql:
  apex_redis: