[tool]
[tool.pdm]

[project]
name = "Fastapi_tortoise"
version = "0.1.0"
description = "使用fastapi+tortoise-orm构建的demo"
authors = [
    {name = "RicarTang", email = "357965604@qq.com"},
]
dependencies = [
    "pydantic>=1.10.7",
    "fastapi>=0.95.0",
    "passlib>=1.7.4",
    "uvicorn>=0.21.1",
    "python-jose>=3.3.0",
    "python-multipart>=0.0.6",
    "aiomysql>=0.1.1",
    "tortoise-orm>=0.19.3",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.scripts]
dev = "python3 -m uvicorn main:app --reload --port 4000"
pro = "python3 -m uvicorn main:app --port 4000"