"""Initial migration

Revision ID: 01c9060485cc
Revises: 
Create Date: 2024-09-01 19:37:18.147594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c9060485cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_user',
    sa.Column('user_name', sa.String(length=20), nullable=False, comment='用户名称'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('status', sa.Integer(), nullable=False, comment='用户状态,0:禁用,1:启用'),
    sa.Column('remark', sa.String(length=50), nullable=False, comment='用户名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('delete_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_index(op.f('ix_ap_user_id'), 'ap_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ap_user_id'), table_name='ap_user')
    op.drop_table('ap_user')
    # ### end Alembic commands ###
