from .user import router as user_api
from .comment import router as comment_api
from .admin import router as admin_api
from .testcase import router as testcase_api
from .testsuite import router as testsuite_api
from .testenv import router as testenv_api
from .config import router as config_api
from .sse import router as sse_api
from .default import router as default_api
from .menu import router as menu_api